version: "3"

networks:
  ahp_backend:

services:
  ahp_mysql_server:
    container_name: ahp_mysql_server
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3308:3306
    volumes:
      - ./mysql_database:/var/lib/mysql
    networks:
      - ahp_backend

  ahp_phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ahp_phpmyadmin
    environment:
      - PMA_ARBITRARY=1
    restart: always
    ports:
      - 8080:80
    volumes:
      - /sessions
    depends_on:
      - ahp_mysql_server
    networks:
      - ahp_backend

  app:
    container_name: ahp_app
    image: php:8.1
    build: .
    volumes:
      - "./:/app"
      - "./../packages:/packages"
    working_dir: /app
    command: "php artisan serve --host=0.0.0.0 --port=8000"
    depends_on:
      - ahp_mysql_server
      - ahp_phpmyadmin
    ports:
      - 8000:8000
    networks:
      - ahp_backend